"""Acceptance oracle: detection + message helpers for the "this merge changed
the MCP server's own source" operator notice.

Read-only fixture. The implementation must satisfy these; do not edit this file.
"""
from pipeline import self_modification as sm


class _Proc:
    def __init__(self, returncode=0, stdout=""):
        self.returncode = returncode
        self.stdout = stdout
        self.stderr = ""


class _FakeSubprocess:
    """Stand-in for the `subprocess` module attribute inside the helper."""

    def __init__(self, proc=None, exc=None):
        self._proc = proc
        self._exc = exc
        self.calls = []

    def run(self, cmd, **kwargs):
        self.calls.append((cmd, kwargs))
        if self._exc is not None:
            raise self._exc
        return self._proc


def _fake(stdout="", returncode=0):
    return _FakeSubprocess(proc=_Proc(returncode=returncode, stdout=stdout))


def test_self_source_files_are_the_two_live_server_sources():
    assert set(sm.MCP_SELF_SOURCE_FILES) == {
        "pipeline/server.py",
        "app/pipeline_mcp_server.py",
    }


def test_detects_pipeline_server_py(monkeypatch, tmp_path):
    monkeypatch.setattr(sm, "subprocess", _fake("pipeline/server.py\nREADME.md\n"))
    assert sm._mcp_self_source_touched(str(tmp_path), "origin/master") == [
        "pipeline/server.py"
    ]


def test_detects_app_module_on_its_own(monkeypatch, tmp_path):
    monkeypatch.setattr(sm, "subprocess", _fake("app/pipeline_mcp_server.py\n"))
    assert sm._mcp_self_source_touched(str(tmp_path), "origin/master") == [
        "app/pipeline_mcp_server.py"
    ]


def test_both_files_are_each_reported_once(monkeypatch, tmp_path):
    monkeypatch.setattr(
        sm,
        "subprocess",
        _fake("app/pipeline_mcp_server.py\npipeline/server.py\ndocs/x.md\n"),
    )
    touched = sm._mcp_self_source_touched(str(tmp_path), "origin/master")
    assert len(touched) == 2
    assert sorted(touched) == ["app/pipeline_mcp_server.py", "pipeline/server.py"]


def test_unrelated_diff_including_the_test_file_returns_empty(monkeypatch, tmp_path):
    # Substring matching would wrongly hit tests/unit/test_pipeline_mcp_server.py.
    monkeypatch.setattr(
        sm,
        "subprocess",
        _fake("pipeline/rebase.py\ntests/unit/test_pipeline_mcp_server.py\n"),
    )
    assert sm._mcp_self_source_touched(str(tmp_path), "origin/master") == []


def test_git_nonzero_exit_fails_open(monkeypatch, tmp_path):
    monkeypatch.setattr(
        sm, "subprocess", _fake("pipeline/server.py\n", returncode=128)
    )
    assert sm._mcp_self_source_touched(str(tmp_path), "origin/master") == []


def test_oserror_fails_open(monkeypatch, tmp_path):
    monkeypatch.setattr(
        sm, "subprocess", _FakeSubprocess(exc=OSError("git missing"))
    )
    assert sm._mcp_self_source_touched(str(tmp_path), "origin/master") == []


def test_missing_worktree_never_shells_out(monkeypatch):
    fake = _fake("pipeline/server.py\n")
    monkeypatch.setattr(sm, "subprocess", fake)
    assert sm._mcp_self_source_touched("/nonexistent/worktree", "origin/master") == []
    assert fake.calls == []


def test_empty_worktree_string_fails_open(monkeypatch):
    fake = _fake("pipeline/server.py\n")
    monkeypatch.setattr(sm, "subprocess", fake)
    assert sm._mcp_self_source_touched("", "origin/master") == []
    assert fake.calls == []


def test_notice_names_every_file_and_the_reconnect_action():
    msg = sm._mcp_restart_notice(
        ["pipeline/server.py", "app/pipeline_mcp_server.py"]
    )
    assert "pipeline/server.py" in msg
    assert "app/pipeline_mcp_server.py" in msg
    assert "/mcp reconnect" in msg
